name: Auto PR Description

on:
  pull_request:
    types: [opened]

jobs:
  copy_issue_description:
    runs-on: ubuntu-latest

    steps:
    - name: Get Issue Number from Branch Name
      id: issue
      run: |
        echo "::set-output name=issue_number::$(echo "${{ github.event.pull_request.head.ref }}" | grep -o '[0-9]\+')"

    - name: Get Issue Description
      id: issue_description
      uses: actions/github-script@v6
      with:
        script: |
          const issue_number = ${{ steps.issue.outputs.issue_number }};
          const issue = await github.rest.issues.get({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: issue_number
          });
          return issue.data.body;

    - name: Update Pull Request Description
      uses: actions/github-script@v6
      with:
        script: |
          const pr_number = context.payload.pull_request.number;
          const issue_body = ${{ steps.issue_description.outputs.result }};
          await github.rest.pulls.update({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: pr_number,
            body: `This PR addresses issue #${{ steps.issue.outputs.issue_number }}\n\nIssue Description:\n${issue_body}`
          });