name: Auto PR Description

on:
  pull_request:
    types: [opened]

jobs:
  copy_issue_description:
    runs-on: ubuntu-latest

    steps:
    - name: Extract Issue Number from Branch Name
      id: issue
      run: |
        # Extract the first number found in the branch name
        ISSUE_NUMBER=$(echo "${{ github.event.pull_request.head.ref }}" | grep -oE '^[0-9]+')
        echo "Extracted Issue Number: $ISSUE_NUMBER"
        echo "::set-output name=issue_number::$ISSUE_NUMBER"

    - name: Check Issue Number Validity
      if: steps.issue.outputs.issue_number == ''
      run: |
        echo "No valid issue number found in branch name. Please ensure the branch name includes the issue number."
        exit 1

    - name: Get Issue Description
      id: issue_description
      uses: actions/github-script@v6
      with:
        script: |
          const issue_number = ${{ steps.issue.outputs.issue_number }};
          if (!issue_number) {
            throw new Error("No issue number found.");
          }
          const issue = await github.rest.issues.get({
            owner: context.repo.owner,
            repo: context.repo.repo,