name: Set PR Title and Link

on:
  pull_request:
    types: [opened]

jobs:
  update_pr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Set PR title and add issue link
      run: |
        # Get the branch name
        branch_name="${{ github.head_ref }}"
        
        # Extract issue number from branch name (assuming format issue-<issue-number>-<title>)
        issue_number=$(echo "$branch_name" | grep -oP 'issue-\K[0-9]+')
        
        # Get the issue title
        issue_title=$(gh issue view "$issue_number" --json title -q ".title")
        
        # Set the PR title to the branch name
        gh pr edit ${{ github.event.pull_request.number }} --title "$branch_name"
        
        # Add a comment with the issue link
        issue_link="https://github.com/${{ github.repository }}/issues/$issue_number"
        comment_body="Related issue: [$issue_title]($issue_link)"
        gh pr comment ${{ github.event.pull_request.number }} --body "$comment_body"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}