name: Update Issue Status on PR

on:
  pull_request:
    types: [opened]

jobs:
  update_status:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Get issue number from branch name
      id: get_issue_number
      run: |
        branch_name="${{ github.head_ref }}"
        issue_number=$(echo "$branch_name" | sed -E 's/^issue-([0-9]+)-.*$/\1/')
        echo "::set-output name=issue_number::$issue_number"

    - name: Update issue custom field
      run: |
        issue_number="${{ steps.get_issue_number.outputs.issue_number }}"
        # Assuming you have a command or API call to update the custom field
        # Replace this with your actual command/API
        gh api -X PATCH "/repos/${{ github.repository }}/issues/$issue_number" -f custom_fields='{"Status":"In Test"}'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}