name: Comment on Issue When PR Created

on:
  pull_request:
    types: [opened]

jobs:
  comment_issue:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Get issue number from branch name
      id: get_issue_number
      run: |
        branch_name="${{ github.head_ref }}"
        issue_number=$(echo "$branch_name" | sed -E 's/^issue-([0-9]+)-.*$/\1/')
        echo "ISSUE_NUMBER=$issue_number" >> $GITHUB_ENV

    - name: Comment on the issue with status
      run: |
        issue_number="${{ env.ISSUE_NUMBER }}"
        comment_body="Status: In Test"
        gh issue comment $issue_number --body "$comment_body"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}